QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 100 } } },
	lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 50 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },
	-- angelicsx-Civilianjobs
	busdriver = { label = 'Bus Driver', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	forkliftdriver = { label = 'Forklift Operator', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	taxidriver = { label = 'Taxi Driver', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	scubadiver = { label = 'Scuba Diver', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	lifeguard = { label = 'Lifeguard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	helidriver = { label = 'Helicopter Cargo Delivery', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbagedriver = { label = 'Garbage Truck Driver', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },

	police = {
		label = 'Law Enforcement',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Officer', payment = 75 },
			['2'] = { name = 'Sergeant', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Chief', isboss = true, payment = 150 },
		},
	},
	lspd = {
		label = 'Los Santos Police Department',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Officer', payment = 75 },
			['2'] = { name = 'Sergeant', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Chief', isboss = true, payment = 150 },
		},
	},
	bcso = {
		label = 'Blaine County Sheriffs Office',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Officer', payment = 75 },
			['2'] = { name = 'Sergeant', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Chief', isboss = true, payment = 150 },
		},
	},
	sasp = {
		label = 'San Andreas State Police',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Officer', payment = 75 },
			['2'] = { name = 'Sergeant', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Chief', isboss = true, payment = 150 },
		},
	},
	sapr = {
		label = 'San Andreas Park Rangers',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Officer', payment = 75 },
			['2'] = { name = 'Sergeant', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Chief', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Paramedic', payment = 75 },
			['2'] = { name = 'Doctor', payment = 100 },
			['3'] = { name = 'Surgeon', payment = 125 },
			['4'] = { name = 'Chief', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 75 },
			['2'] = { name = 'Event Driver', payment = 100 },
			['3'] = { name = 'Sales', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	postal = { -- dream-postal
		label = 'GoPostal',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Delivery Driver', payment = 0 },
			['1'] = { name = 'Manager', payment = 0 },
			['2'] = { name = 'Boss', isboss = true, payment = 0 },
		},
	},
	butcher = { -- lusty94_butcher
		label = 'Clucking Bell Butcher',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Apprentice Butcher', payment = 50 },
			['1'] = { name = 'Novice Butcher', payment = 50 },
			['2'] = { name = 'Professional Butcher', payment = 50 },
			['3'] = { name = 'Senior Butcher', payment = 50 },
			['4'] = { name = 'Butchery Owner', isboss = true, payment = 50},
		},
	},
	airport = { -- pickle-airport
		label = 'Airport',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Pilot', payment = 0 },
			['2'] = { name = 'Lead Pilot', payment = 0 },
			['3'] = { name = 'Air-Traffic Controller', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	pdmdealer = {
		label = 'Car Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	pdmdealer2 = {
		label = 'Car Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	luxaryautos = {
		label = 'Car Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	paletoautos = {
		label = 'Car Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cayoautos = {
		label = 'Car Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	foximportdealer = {
		label = 'Car Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	lsmechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	lsmechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	airmechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	lsmechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	delmechanic = {
		label = 'Del Pierro Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	sandymechanic = {
		label = 'Sandy Shores Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cayomechanic = {
		label = 'Cayo Perico Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	gangmechanic = {
		label = 'Gang Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taximechanic = {
		label = 'Gang Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	autoexoticmechanic = {
		label = 'Auto Exotic Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	dealermechanic = {
		label = 'Premium Deluxe Motorsport Dealership',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	dealermechanic2 = {
		label = 'Paleto Car Dealership',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	vankhov = { 
		label = 'Vankhov Jewlers',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	ammunation = { 
		label = 'Ammunation',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	pawnshop = { 
		label = 'Pawnshop',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	sandypawnshop = { 
		label = 'Electronics Shop',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	pharmacy = { 
		label = 'Pharmacy',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	burgershot = { 
		label = 'Burgershot',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	hoboburgerburger = { 
		label = 'Hobo Burger',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	chihuahua = { 
		label = 'Chihuahua Dogs',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	luckyplucker = { 
		label = 'Lucky Plucker',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	luckyplucker2 = { 
		label = 'Lucky Plucker',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	cluckinbell = { 
		label = 'Cluckin Bell',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	subway = { 
		label = 'Subway',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	tacobomb = { 
		label = 'Taco Bomb',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	tacobell = { 
		label = 'Taco Bell',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	paletodinner = { 
		label = 'Paleto Dinner',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	pipeline = { 
		label = 'Pipeline Dinner',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	venetian = { 
		label = 'Venetian',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	jacuzzidinner = { 
		label = 'Jacuzzi Dinner',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	hookies = { 
		label = 'Hookies',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	galdinquay = { 
		label = 'Galdin Quay',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	yellowjacket = { 
		label = 'Yellow Jacket',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	cayopericodinner = { 
		label = 'Cayo Perico Dinner',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	salierisbar = { 
		label = 'Salieris Bar',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	lostbar = { 
		label = 'Lost Mc Bar',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	tequila = { 
		label = 'Tequila',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	cayopericobar = { 
		label = 'Cayo Perico Bar',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	himen = { 
		label = 'Hi-Men',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	hookah = { 
		label = 'Hookah Lounge',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	bahamamamas = { 
		label = 'Bahama Mamas',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	apollobar = { 
		label = 'Apollo Bar',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	unicorn = { 
		label = 'Unicorn Club',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	autoexoticbar = { 
		label = 'Auto Exotic Bar',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	polarice = { 
		label = 'Polar Ice',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	serenity = { 
		label = 'Serenity Dispensary',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
	bestbuds = { 
		label = 'Best Buds Dispensary',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 0 },
			['1'] = { name = 'Employee', payment = 0 },
			['2'] = { name = 'Assistant Manager', payment = 0 },
			['3'] = { name = 'Manager', payment = 0 },
			['4'] = { name = 'Owner', isboss = true,  bankAuth = true, payment = 0 },
		},
	},
}
